/**
 * Search Intent Coverage Matrix для chip-net.ru
 *
 * Комплексная матрица поисковых интентов B2B-рынка полупроводников
 * в России. Обеспечивает 100% покрытие всех типов поисковых запросов:
 * закупка, аналоги, даташиты, сравнения, информационные, BOM/комплектация,
 * импортозамещение.
 *
 * Используется для:
 * - SEO-стратегии и создания недостающих страниц
 * - Контент-планирования (блог, база знаний)
 * - Мониторинга покрытия поисковых интентов
 * - Приоритизации создания новых посадочных страниц
 */

// ─── Интерфейсы ────────────────────────────────────────────────────────────────

export interface SearchIntent {
  id: string;
  /** Поисковый запрос (шаблон) */
  query: string;
  /** Тип интента */
  intentType:
    | 'purchase'
    | 'analog'
    | 'datasheet'
    | 'comparison'
    | 'info'
    | 'bom'
    | 'pricing'
    | 'availability'
    | 'specification'
    | 'replacement'
    | 'import-substitution';
  /** Целевая страница или шаблон URL */
  targetUrl: string;
  /** Приоритет (1=высший) */
  priority: number;
  /** Покрыт ли этот интент существующей страницей */
  covered: boolean;
  /** Объём поиска: high/medium/low */
  searchVolume: 'high' | 'medium' | 'low';
  /** Связанные сущности */
  relatedEntities: string[];
}

// ─── Данные: 160 поисковых интентов ────────────────────────────────────────────

export const searchIntents: SearchIntent[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // PURCHASE INTENTS (32)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'purch-001',
    query: 'купить STM32F103C8T6 оптом',
    intentType: 'purchase',
    targetUrl: '/component/STM32F103C8T6',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103C8T6', 'STMicroelectronics', 'микроконтроллеры'],
  },
  {
    id: 'purch-002',
    query: 'купить FPGA Artix-7',
    intentType: 'purchase',
    targetUrl: '/brand/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['XC7A35T', 'Xilinx', 'ПЛИС'],
  },
  {
    id: 'purch-003',
    query: 'купить микроконтроллеры оптом',
    intentType: 'purchase',
    targetUrl: '/mikrokontrollery',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['микроконтроллеры', 'MCU', 'STM32', 'GD32'],
  },
  {
    id: 'purch-004',
    query: 'купить ПЛИС Xilinx',
    intentType: 'purchase',
    targetUrl: '/plis',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Xilinx', 'ПЛИС', 'FPGA'],
  },
  {
    id: 'purch-005',
    query: 'купить аналоги STM32',
    intentType: 'purchase',
    targetUrl: '/analogs',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32', 'GD32', 'аналоги'],
  },
  {
    id: 'purch-006',
    query: 'купить конденсаторы керамические оптом',
    intentType: 'purchase',
    targetUrl: '/keramicheskie-kondensatory',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['конденсаторы', 'MLCC', 'керамика'],
  },
  {
    id: 'purch-007',
    query: 'купить транзисторы MOSFET оптом',
    intentType: 'purchase',
    targetUrl: '/tranzistory-mosfet',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['MOSFET', 'транзисторы', 'IRF', 'N-Channel'],
  },
  {
    id: 'purch-008',
    query: 'купить операционные усилители',
    intentType: 'purchase',
    targetUrl: '/operatsionnye-usiliteli',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['LM358', 'TL072', 'NE5532', 'ОУ'],
  },
  {
    id: 'purch-009',
    query: 'купить стабилизаторы напряжения',
    intentType: 'purchase',
    targetUrl: '/stabilizatory-napryazheniya',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['LM7805', 'AMS1117', 'LM2596', 'LDO'],
  },
  {
    id: 'purch-010',
    query: 'купить резисторы SMD оптом',
    intentType: 'purchase',
    targetUrl: '/rezistory-smd',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['резисторы', 'SMD', '0402', '0603', '0805'],
  },
  {
    id: 'purch-011',
    query: 'купить микросхемы памяти DDR',
    intentType: 'purchase',
    targetUrl: '/mikroskhemy-pamyati',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['DDR3', 'DDR4', 'Micron', 'Samsung'],
  },
  {
    id: 'purch-012',
    query: 'купить датчики температуры',
    intentType: 'purchase',
    targetUrl: '/datchiki-temperatury',
    priority: 3,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['DS18B20', 'LM35', 'NTC', 'термисторы'],
  },
  {
    id: 'purch-013',
    query: 'купить разъёмы для печатных плат',
    intentType: 'purchase',
    targetUrl: '/razemy-dlya-pechatnykh-plat',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['разъёмы', 'Pin Header', 'Molex', 'JST'],
  },
  {
    id: 'purch-014',
    query: 'купить микросхемы TI',
    intentType: 'purchase',
    targetUrl: '/brand/texas-instruments',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Texas Instruments', 'TI', 'LM', 'TPS'],
  },
  {
    id: 'purch-015',
    query: 'купить DAC ADC конвертеры',
    intentType: 'purchase',
    targetUrl: '/ats-tsap-konvertery',
    priority: 3,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['ADC', 'DAC', 'MCP3208', 'ADS1115'],
  },
  {
    id: 'purch-016',
    query: 'купить радиокомпоненты для производства',
    intentType: 'purchase',
    targetUrl: '/catalog',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['производство', 'BOM', 'комплектация'],
  },
  {
    id: 'purch-017',
    query: 'купить микросхемы Infineon',
    intentType: 'purchase',
    targetUrl: '/brand/infineon',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Infineon', 'IGBT', 'MOSFET', 'XMC'],
  },
  {
    id: 'purch-018',
    query: 'купить оптопары оптом',
    intentType: 'purchase',
    targetUrl: '/optopary',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['PC817', '6N137', 'оптопары', 'оптроны'],
  },
  {
    id: 'purch-019',
    query: 'купить интерфейсные микросхемы',
    intentType: 'purchase',
    targetUrl: '/interfeysnye-mikroskhemy',
    priority: 3,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['MAX232', 'FT232RL', 'RS485', 'CAN'],
  },
  {
    id: 'purch-020',
    query: 'купить электролитические конденсаторы',
    intentType: 'purchase',
    targetUrl: '/elektroliticheskie-kondensatory',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['электролиты', 'конденсаторы', 'Nichicon', 'Panasonic'],
  },
  {
    id: 'purch-021',
    query: 'купить индуктивности и дроссели',
    intentType: 'purchase',
    targetUrl: '/induktivnosti-drosseli',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['индуктивности', 'дроссели', 'Murata', 'Würth'],
  },
  {
    id: 'purch-022',
    query: 'купить диоды Шоттки оптом',
    intentType: 'purchase',
    targetUrl: '/diody-shottki',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['диоды', 'Шоттки', 'SS34', '1N5819'],
  },
  {
    id: 'purch-023',
    query: 'купить кварцевые резонаторы',
    intentType: 'purchase',
    targetUrl: '/kvartsevye-rezonatory',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['кварц', 'резонатор', '8MHz', '16MHz', '32.768kHz'],
  },
  {
    id: 'purch-024',
    query: 'купить микросхемы NXP',
    intentType: 'purchase',
    targetUrl: '/brand/nxp',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['NXP', 'LPC', 'i.MX', 'Kinetis'],
  },
  {
    id: 'purch-025',
    query: 'купить реле управления',
    intentType: 'purchase',
    targetUrl: '/rele-upravleniya',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['реле', 'Omron', 'твердотельные реле'],
  },
  {
    id: 'purch-026',
    query: 'купить микросхемы Analog Devices',
    intentType: 'purchase',
    targetUrl: '/brand/analog-devices',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Analog Devices', 'ADI', 'AD', 'операционные усилители'],
  },
  {
    id: 'purch-027',
    query: 'заказать электронные компоненты для предприятия',
    intentType: 'purchase',
    targetUrl: '/bom',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['B2B', 'комплектация', 'закупка', 'предприятие'],
  },
  {
    id: 'purch-028',
    query: 'купить микросхемы Microchip',
    intentType: 'purchase',
    targetUrl: '/brand/microchip',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Microchip', 'PIC', 'ATmega', 'AVR'],
  },
  {
    id: 'purch-029',
    query: 'купить силовые модули IGBT',
    intentType: 'purchase',
    targetUrl: '/silovye-moduli-igbt',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['IGBT', 'Infineon', 'силовая электроника', 'IPM'],
  },
  {
    id: 'purch-030',
    query: 'купить LED драйверы',
    intentType: 'purchase',
    targetUrl: '/led-drayvery',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['LED', 'драйвер', 'WS2811', 'AL8805'],
  },
  {
    id: 'purch-031',
    query: 'купить микросхемы Renesas',
    intentType: 'purchase',
    targetUrl: '/brand/renesas',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Renesas', 'RL78', 'RA', 'RX'],
  },
  {
    id: 'purch-032',
    query: 'купить модули беспроводной связи',
    intentType: 'purchase',
    targetUrl: '/moduli-besprovodnoy-svyazi',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['WiFi', 'Bluetooth', 'LoRa', 'Nordic', 'nRF52'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ANALOG / REPLACEMENT INTENTS (27)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'anlg-001',
    query: 'аналог STM32F103C8T6',
    intentType: 'analog',
    targetUrl: '/analog/STM32F103C8T6',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103C8T6', 'GD32F103C8T6', 'CH32F103C8T6', 'APM32F103C8T6'],
  },
  {
    id: 'anlg-002',
    query: 'замена STM32F407VGT6',
    intentType: 'replacement',
    targetUrl: '/analog/STM32F407VGT6',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F407VGT6', 'GD32F407VET6', 'AT32F407VGT7'],
  },
  {
    id: 'anlg-003',
    query: 'аналог Xilinx Artix-7',
    intentType: 'analog',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Artix-7', 'Gowin', 'ECP5', 'Lattice'],
  },
  {
    id: 'anlg-004',
    query: 'аналог XC7A35T',
    intentType: 'analog',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['XC7A35T', 'Gowin GW1N', 'Lattice ECP5'],
  },
  {
    id: 'anlg-005',
    query: 'замена TPS5430',
    intentType: 'replacement',
    targetUrl: '/ti',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['TPS5430', 'MP1584', 'LM2596', 'SY8120'],
  },
  {
    id: 'anlg-006',
    query: 'аналог LM2596',
    intentType: 'analog',
    targetUrl: '/analog/LM2596',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['LM2596', 'MP1584', 'XL2596', 'SY8120'],
  },
  {
    id: 'anlg-007',
    query: 'аналог AMS1117-3.3',
    intentType: 'analog',
    targetUrl: '/analog/AMS1117-3.3',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['AMS1117-3.3', 'LD1117', 'XC6206', 'RT9193'],
  },
  {
    id: 'anlg-008',
    query: 'кросс-референс STM32',
    intentType: 'analog',
    targetUrl: '/analogs',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32', 'GD32', 'CH32', 'APM32', 'кросс-референс'],
  },
  {
    id: 'anlg-009',
    query: 'аналог FT232RL',
    intentType: 'analog',
    targetUrl: '/analog/FT232RL',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['FT232RL', 'CH340G', 'CP2102', 'PL2303'],
  },
  {
    id: 'anlg-010',
    query: 'замена SP3485',
    intentType: 'replacement',
    targetUrl: '/analog/SP3485',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['SP3485', 'SN65HVD485', 'MAX485', 'ST3485'],
  },
  {
    id: 'anlg-011',
    query: 'аналог LM7805',
    intentType: 'analog',
    targetUrl: '/analog/LM7805',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['LM7805', 'L7805', 'MC7805', 'KA7805'],
  },
  {
    id: 'anlg-012',
    query: 'аналог MAX232',
    intentType: 'analog',
    targetUrl: '/analog/MAX232',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['MAX232', 'ST232', 'HIN232', 'SP3232'],
  },
  {
    id: 'anlg-013',
    query: 'замена ATmega328P',
    intentType: 'replacement',
    targetUrl: '/analog/ATmega328P',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['ATmega328P', 'LGT8F328P', 'CH32V003'],
  },
  {
    id: 'anlg-014',
    query: 'аналог PC817',
    intentType: 'analog',
    targetUrl: '/analog/PC817',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['PC817', 'EL817', 'CNY17', 'LTV817'],
  },
  {
    id: 'anlg-015',
    query: 'аналог IRFZ44N',
    intentType: 'analog',
    targetUrl: '/analog/IRFZ44N',
    priority: 3,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['IRFZ44N', 'IRF540N', 'FQP30N06L', 'STP55NF06L'],
  },
  {
    id: 'anlg-016',
    query: 'замена NE555',
    intentType: 'replacement',
    targetUrl: '/analog/NE555',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['NE555', 'LM555', 'TLC555', 'SA555'],
  },
  {
    id: 'anlg-017',
    query: 'аналог TL431',
    intentType: 'analog',
    targetUrl: '/analog/TL431',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['TL431', 'KA431', 'LM431', 'AT431'],
  },
  {
    id: 'anlg-018',
    query: 'аналог DS18B20',
    intentType: 'analog',
    targetUrl: '/analog/DS18B20',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['DS18B20', 'DS1822', 'GND18B20', 'TY18B20'],
  },
  {
    id: 'anlg-019',
    query: 'замена ESP32',
    intentType: 'replacement',
    targetUrl: '/analog/ESP32',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['ESP32', 'BK7251', 'W800', 'CH582'],
  },
  {
    id: 'anlg-020',
    query: 'кросс-референс аналогов микросхем',
    intentType: 'analog',
    targetUrl: '/analogs',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['кросс-референс', 'аналоги', 'замены', 'микросхемы'],
  },
  {
    id: 'anlg-021',
    query: 'аналог LP2985',
    intentType: 'analog',
    targetUrl: '/analog/LP2985',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['LP2985', 'RT9193', 'XC6206', 'ME6211'],
  },
  {
    id: 'anlg-022',
    query: 'замена 74HC595',
    intentType: 'replacement',
    targetUrl: '/analog/74HC595',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['74HC595', '74HCT595', 'CD74HC595', 'M74HC595'],
  },
  {
    id: 'anlg-023',
    query: 'аналог MCP2551',
    intentType: 'analog',
    targetUrl: '/analog/MCP2551',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['MCP2551', 'TJA1050', 'SN65HVD230', 'PCA82C250'],
  },
  {
    id: 'anlg-024',
    query: 'замена W25Q32',
    intentType: 'replacement',
    targetUrl: '/analog/W25Q32',
    priority: 3,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['W25Q32', 'GD25Q32', 'XM25QH32', 'ZB25VQ32'],
  },
  {
    id: 'anlg-025',
    query: 'аналог LM358',
    intentType: 'analog',
    targetUrl: '/analog/LM358',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['LM358', 'NE5532', 'TL072', 'RC4558'],
  },
  {
    id: 'anlg-026',
    query: 'замена IR2110',
    intentType: 'replacement',
    targetUrl: '/analog/IR2110',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['IR2110', 'IR2113', 'HIP4082', 'FD6288'],
  },
  {
    id: 'anlg-027',
    query: 'аналог CP2102',
    intentType: 'analog',
    targetUrl: '/analog/CP2102',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['CP2102', 'CH340G', 'FT232RL', 'PL2303'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // DATASHEET INTENTS (17)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'ds-001',
    query: 'даташит STM32F103',
    intentType: 'datasheet',
    targetUrl: '/datasheet/STM32F103C8T6',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103', 'даташит', 'STMicroelectronics'],
  },
  {
    id: 'ds-002',
    query: 'даташит XC7A35T',
    intentType: 'datasheet',
    targetUrl: '/datasheet/XC7A35T',
    priority: 1,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['XC7A35T', 'Artix-7', 'Xilinx', 'даташит'],
  },
  {
    id: 'ds-003',
    query: 'datasheet LM358',
    intentType: 'datasheet',
    targetUrl: '/datasheet/LM358',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['LM358', 'даташит', 'TI', 'операционный усилитель'],
  },
  {
    id: 'ds-004',
    query: 'даташит PC817',
    intentType: 'datasheet',
    targetUrl: '/datasheet/PC817',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['PC817', 'даташит', 'оптопара', 'Sharp'],
  },
  {
    id: 'ds-005',
    query: 'даташит ESP32',
    intentType: 'datasheet',
    targetUrl: '/datasheet/ESP32-WROOM-32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['ESP32', 'даташит', 'Espressif', 'WiFi'],
  },
  {
    id: 'ds-006',
    query: 'datasheet TPS5430',
    intentType: 'datasheet',
    targetUrl: '/datasheet/TPS5430',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['TPS5430', 'даташит', 'TI', 'DC-DC'],
  },
  {
    id: 'ds-007',
    query: 'даташит IRFZ44N',
    intentType: 'datasheet',
    targetUrl: '/datasheet/IRFZ44N',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['IRFZ44N', 'даташит', 'MOSFET', 'Vishay'],
  },
  {
    id: 'ds-008',
    query: 'datasheet ATmega328P',
    intentType: 'datasheet',
    targetUrl: '/datasheet/ATmega328P',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['ATmega328P', 'даташит', 'Microchip', 'AVR'],
  },
  {
    id: 'ds-009',
    query: 'даташит LM2596',
    intentType: 'datasheet',
    targetUrl: '/datasheet/LM2596',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['LM2596', 'даташит', 'TI', 'Step-Down'],
  },
  {
    id: 'ds-010',
    query: 'даташит STM32F407',
    intentType: 'datasheet',
    targetUrl: '/datasheet/STM32F407VGT6',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F407', 'даташит', 'STMicroelectronics'],
  },
  {
    id: 'ds-011',
    query: 'datasheet NE555',
    intentType: 'datasheet',
    targetUrl: '/datasheet/NE555',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['NE555', 'даташит', 'таймер', 'TI'],
  },
  {
    id: 'ds-012',
    query: 'даташит GD32F103',
    intentType: 'datasheet',
    targetUrl: '/datasheet/GD32F103C8T6',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['GD32F103', 'даташит', 'GigaDevice'],
  },
  {
    id: 'ds-013',
    query: 'datasheet TL431',
    intentType: 'datasheet',
    targetUrl: '/datasheet/TL431',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['TL431', 'даташит', 'референс', 'TI'],
  },
  {
    id: 'ds-014',
    query: 'даташит FT232RL',
    intentType: 'datasheet',
    targetUrl: '/datasheet/FT232RL',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['FT232RL', 'даташит', 'FTDI', 'USB-UART'],
  },
  {
    id: 'ds-015',
    query: 'datasheet W25Q32',
    intentType: 'datasheet',
    targetUrl: '/datasheet/W25Q32',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['W25Q32', 'даташит', 'Winbond', 'Flash'],
  },
  {
    id: 'ds-016',
    query: 'даташит AMS1117-3.3',
    intentType: 'datasheet',
    targetUrl: '/datasheet/AMS1117-3.3',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['AMS1117-3.3', 'даташит', 'LDO', 'Advanced Monolithic Systems'],
  },
  {
    id: 'ds-017',
    query: 'datasheet STM32H743',
    intentType: 'datasheet',
    targetUrl: '/datasheet/STM32H743VIT6',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['STM32H743', 'даташит', 'STMicroelectronics', 'Cortex-M7'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // COMPARISON INTENTS (17)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'cmp-001',
    query: 'STM32 vs GD32',
    intentType: 'comparison',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32', 'GD32', 'STMicroelectronics', 'GigaDevice'],
  },
  {
    id: 'cmp-002',
    query: 'Artix-7 vs Cyclone V',
    intentType: 'comparison',
    targetUrl: '/fpga-hub',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Artix-7', 'Cyclone V', 'Xilinx', 'Altera'],
  },
  {
    id: 'cmp-003',
    query: 'LM358 vs TL072',
    intentType: 'comparison',
    targetUrl: '/compare/LM358-vs-TL072',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['LM358', 'TL072', 'операционные усилители'],
  },
  {
    id: 'cmp-004',
    query: 'TPS5430 vs MP1584',
    intentType: 'comparison',
    targetUrl: '/compare/TPS5430-vs-MP1584',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['TPS5430', 'MP1584', 'DC-DC', 'Step-Down'],
  },
  {
    id: 'cmp-005',
    query: 'Xilinx vs Altera',
    intentType: 'comparison',
    targetUrl: '/fpga-hub',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Xilinx', 'Altera', 'FPGA', 'ПЛИС'],
  },
  {
    id: 'cmp-006',
    query: 'ESP32 vs STM32',
    intentType: 'comparison',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['ESP32', 'STM32', 'микроконтроллеры', 'WiFi'],
  },
  {
    id: 'cmp-007',
    query: 'ATmega328P vs STM32F103',
    intentType: 'comparison',
    targetUrl: '/compare/ATmega328P-vs-STM32F103',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['ATmega328P', 'STM32F103', 'AVR', 'ARM'],
  },
  {
    id: 'cmp-008',
    query: 'LM2596 vs MP1584',
    intentType: 'comparison',
    targetUrl: '/compare/LM2596-vs-MP1584',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['LM2596', 'MP1584', 'Step-Down', 'DC-DC'],
  },
  {
    id: 'cmp-009',
    query: 'RISC-V vs ARM',
    intentType: 'comparison',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['RISC-V', 'ARM', 'Cortex-M', 'архитектура'],
  },
  {
    id: 'cmp-010',
    query: 'CH340G vs CP2102 vs FT232RL',
    intentType: 'comparison',
    targetUrl: '/compare/CH340G-vs-CP2102-vs-FT232RL',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['CH340G', 'CP2102', 'FT232RL', 'USB-UART'],
  },
  {
    id: 'cmp-011',
    query: 'AMS1117 vs LD1117',
    intentType: 'comparison',
    targetUrl: '/compare/AMS1117-vs-LD1117',
    priority: 3,
    covered: true,
    searchVolume: 'low',
    relatedEntities: ['AMS1117', 'LD1117', 'LDO', '3.3V'],
  },
  {
    id: 'cmp-012',
    query: 'Gowin vs Lattice FPGA',
    intentType: 'comparison',
    targetUrl: '/compare/Gowin-vs-Lattice',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['Gowin', 'Lattice', 'FPGA', 'ПЛИС'],
  },
  {
    id: 'cmp-013',
    query: 'GD32 vs APM32 vs CH32',
    intentType: 'comparison',
    targetUrl: '/compare/GD32-vs-APM32-vs-CH32',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['GD32', 'APM32', 'CH32', 'аналоги STM32'],
  },
  {
    id: 'cmp-014',
    query: 'LM7805 vs AMS1117',
    intentType: 'comparison',
    targetUrl: '/compare/LM7805-vs-AMS1117',
    priority: 3,
    covered: true,
    searchVolume: 'low',
    relatedEntities: ['LM7805', 'AMS1117', 'линейный стабилизатор', 'LDO'],
  },
  {
    id: 'cmp-015',
    query: 'Nordic nRF52 vs ESP32 Bluetooth',
    intentType: 'comparison',
    targetUrl: '/compare/nRF52-vs-ESP32-BLE',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['nRF52832', 'ESP32', 'BLE', 'Bluetooth'],
  },
  {
    id: 'cmp-016',
    query: 'LM358 vs NE5532',
    intentType: 'comparison',
    targetUrl: '/compare/LM358-vs-NE5532',
    priority: 3,
    covered: true,
    searchVolume: 'low',
    relatedEntities: ['LM358', 'NE5532', 'операционные усилители', 'аудио'],
  },
  {
    id: 'cmp-017',
    query: 'IGBT vs MOSFET силовые ключи',
    intentType: 'comparison',
    targetUrl: '/compare/IGBT-vs-MOSFET',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['IGBT', 'MOSFET', 'силовая электроника', 'ключи'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // INFO INTENTS (17)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'info-001',
    query: 'что такое FPGA',
    intentType: 'info',
    targetUrl: '/knowledge-base/chto-takoe-fpga',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['FPGA', 'ПЛИС', 'Xilinx', 'Altera'],
  },
  {
    id: 'info-002',
    query: 'как выбрать микроконтроллер',
    intentType: 'info',
    targetUrl: '/knowledge-base/kak-vybrat-mikrokontroller',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['микроконтроллер', 'STM32', 'ESP32', 'выбор MCU'],
  },
  {
    id: 'info-003',
    query: 'типы корпусов микросхем',
    intentType: 'info',
    targetUrl: '/knowledge-base/tipy-korpusov-mikroskhem',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['корпуса', 'QFP', 'BGA', 'QFN', 'SOP'],
  },
  {
    id: 'info-004',
    query: 'STM32 серии отличия',
    intentType: 'info',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F0', 'STM32F1', 'STM32F4', 'STM32H7'],
  },
  {
    id: 'info-005',
    query: 'импортозамещение электроники',
    intentType: 'info',
    targetUrl: '/knowledge-base/importozameshchenie-elektroniki',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['импортозамещение', 'санкции', 'аналоги', 'Россия'],
  },
  {
    id: 'info-006',
    query: 'проверка оригинальности микросхем',
    intentType: 'info',
    targetUrl: '/anti-counterfeit',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['контрафакт', 'подделки', 'верификация', 'оригинал'],
  },
  {
    id: 'info-007',
    query: 'как читать даташит',
    intentType: 'info',
    targetUrl: '/datasheets',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['даташит', 'спецификация', 'документация'],
  },
  {
    id: 'info-008',
    query: 'типы памяти микросхем',
    intentType: 'info',
    targetUrl: '/knowledge-base/tipy-pamyati-mikroskhem',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['SRAM', 'DRAM', 'Flash', 'EEPROM'],
  },
  {
    id: 'info-009',
    query: 'протоколы связи микроконтроллеров',
    intentType: 'info',
    targetUrl: '/knowledge-base/protokoly-svyazi-mku',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['SPI', 'I2C', 'UART', 'CAN'],
  },
  {
    id: 'info-010',
    query: 'что такое LDO стабилизатор',
    intentType: 'info',
    targetUrl: '/knowledge-base/chto-takoe-ldo-stabilizator',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['LDO', 'стабилизатор', 'AMS1117', 'LD1117'],
  },
  {
    id: 'info-011',
    query: 'системы на кристалле SoC',
    intentType: 'info',
    targetUrl: '/knowledge-base/sistemy-na-kristalle-soc',
    priority: 3,
    covered: false,
    searchVolume: 'low',
    relatedEntities: ['SoC', 'система на кристалле', 'ESP32', 'STM32MP1'],
  },
  {
    id: 'info-012',
    query: 'архитектура ARM Cortex-M',
    intentType: 'info',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['ARM', 'Cortex-M0', 'Cortex-M3', 'Cortex-M4', 'Cortex-M7'],
  },
  {
    id: 'info-013',
    query: 'что такое ШИМ сигнал',
    intentType: 'info',
    targetUrl: '/knowledge-base/chto-takoe-shim-signal',
    priority: 3,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['ШИМ', 'PWM', 'таймер', 'микроконтроллер'],
  },
  {
    id: 'info-014',
    query: 'стандарты качества электронных компонентов',
    intentType: 'info',
    targetUrl: '/quality-assurance',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['качество', 'AEC-Q200', 'MIL-STD', 'ISO'],
  },
  {
    id: 'info-015',
    query: 'как отличить оригинал от подделки микросхему',
    intentType: 'info',
    targetUrl: '/anti-counterfeit',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['контрафакт', 'верификация', 'маркировка', 'оригинал'],
  },
  {
    id: 'info-016',
    query: 'RISC-V архитектура преимущества',
    intentType: 'info',
    targetUrl: '/knowledge-base/risc-v-arkhitektura-preimushchestva',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['RISC-V', 'открытая архитектура', 'GD32V', 'CH32V'],
  },
  {
    id: 'info-017',
    query: 'классификация электронных компонентов',
    intentType: 'info',
    targetUrl: '/knowledge-base/klassifikatsiya-elektronnykh-komponentov',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['классификация', 'пассивные', 'активные', 'электромеханические'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // BOM / PROCUREMENT INTENTS (12)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'bom-001',
    query: 'BOM комплектация',
    intentType: 'bom',
    targetUrl: '/bom',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['BOM', 'комплектация', 'Bill of Materials'],
  },
  {
    id: 'bom-002',
    query: 'комплектация производства электроникой',
    intentType: 'bom',
    targetUrl: '/bom',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['производство', 'комплектация', 'закупка', 'BOM'],
  },
  {
    id: 'bom-003',
    query: 'заказать КП на компоненты',
    intentType: 'bom',
    targetUrl: '/rfq',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['КП', 'коммерческое предложение', 'запрос', 'RFQ'],
  },
  {
    id: 'bom-004',
    query: 'срочная поставка микросхем',
    intentType: 'bom',
    targetUrl: '/urgent-sourcing',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['срочная поставка', 'микросхемы', 'urgent', 'сроки'],
  },
  {
    id: 'bom-005',
    query: 'поставка труднодоступных компонентов',
    intentType: 'bom',
    targetUrl: '/hard-to-find',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['труднодоступные', 'редкие компоненты', 'hard-to-find', 'EOL'],
  },
  {
    id: 'bom-006',
    query: 'закупить электронные компоненты для серийного производства',
    intentType: 'bom',
    targetUrl: '/bom',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['серийное производство', 'BOM', 'оптовая закупка'],
  },
  {
    id: 'bom-007',
    query: 'поставщик электронных компонентов для завода',
    intentType: 'bom',
    targetUrl: '/sourcing-expertise',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['поставщик', 'завод', 'B2B', 'дистрибьютор'],
  },
  {
    id: 'bom-008',
    query: 'аутсорсинг закупки электронных компонентов',
    intentType: 'bom',
    targetUrl: '/bom',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['аутсорсинг', 'закупка', 'комплектация', 'снабжение'],
  },
  {
    id: 'bom-009',
    query: 'комплектация печатных плат компонентами',
    intentType: 'bom',
    targetUrl: '/bom',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['печатная плата', 'комплектация', 'монтаж', 'PCBA'],
  },
  {
    id: 'bom-010',
    query: 'поставка компонентов с истёкшим сроком производства',
    intentType: 'bom',
    targetUrl: '/obsolete',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['obsolete', 'EOL', 'NRND', 'снято с производства'],
  },
  {
    id: 'bom-011',
    query: 'запрос коммерческого предложения на микросхемы',
    intentType: 'bom',
    targetUrl: '/rfq',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['RFQ', 'КП', 'запрос цены', 'коммерческое предложение'],
  },
  {
    id: 'bom-012',
    query: 'доставка электронных компонентов от производителя',
    intentType: 'bom',
    targetUrl: '/delivery',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['доставка', 'логистика', 'производитель', 'сроки'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // PRICING INTENTS (5)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'prc-001',
    query: 'цена STM32F103C8T6',
    intentType: 'pricing',
    targetUrl: '/component/STM32F103C8T6',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103C8T6', 'цена', 'стоимость', 'прайс'],
  },
  {
    id: 'prc-002',
    query: 'прайс лист микросхемы оптом',
    intentType: 'pricing',
    targetUrl: '/catalog',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['прайс', 'оптовые цены', 'прайс-лист'],
  },
  {
    id: 'prc-003',
    query: 'стоимость FPGA Xilinx',
    intentType: 'pricing',
    targetUrl: '/brand/xilinx',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['Xilinx', 'FPGA', 'стоимость', 'цена'],
  },
  {
    id: 'prc-004',
    query: 'оптовые цены на электронные компоненты',
    intentType: 'pricing',
    targetUrl: '/catalog',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['оптовые цены', 'B2B', 'скидки', 'объём'],
  },
  {
    id: 'prc-005',
    query: 'стоимость аналогов STM32',
    intentType: 'pricing',
    targetUrl: '/analogs',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['аналоги', 'STM32', 'цена', 'GD32'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // AVAILABILITY INTENTS (5)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'avail-001',
    query: 'наличие STM32F103C8T6 на складе',
    intentType: 'availability',
    targetUrl: '/component/STM32F103C8T6',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103C8T6', 'склад', 'наличие', 'сток'],
  },
  {
    id: 'avail-002',
    query: 'где купить микросхемы в наличии',
    intentType: 'availability',
    targetUrl: '/catalog',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['в наличии', 'склад', 'микросхемы'],
  },
  {
    id: 'avail-003',
    query: 'наличие ПЛИС на складе Москва',
    intentType: 'availability',
    targetUrl: '/geo/moskva',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['ПЛИС', 'Москва', 'склад', 'наличие'],
  },
  {
    id: 'avail-004',
    query: 'сроки поставки микросхем из-за рубежа',
    intentType: 'availability',
    targetUrl: '/delivery',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['сроки', 'поставка', 'импорт', 'доставка'],
  },
  {
    id: 'avail-005',
    query: 'компоненты в наличии с доставкой',
    intentType: 'availability',
    targetUrl: '/catalog',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['в наличии', 'доставка', 'компоненты'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // SPECIFICATION INTENTS (5)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'spec-001',
    query: 'характеристики STM32F103C8T6',
    intentType: 'specification',
    targetUrl: '/component/STM32F103C8T6',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103C8T6', 'спецификация', 'характеристики', 'Cortex-M3'],
  },
  {
    id: 'spec-002',
    query: 'спецификация LM2596',
    intentType: 'specification',
    targetUrl: '/datasheet/LM2596',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['LM2596', 'спецификация', 'Step-Down', '3A'],
  },
  {
    id: 'spec-003',
    query: 'параметры XC7A35T FPGA',
    intentType: 'specification',
    targetUrl: '/component/XC7A35T',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['XC7A35T', 'Artix-7', 'параметры', 'логические элементы'],
  },
  {
    id: 'spec-004',
    query: 'электрические параметры MOSFET транзисторов',
    intentType: 'specification',
    targetUrl: '/tranzistory-mosfet',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['MOSFET', 'параметры', 'Rds(on)', 'Vgs', 'Id'],
  },
  {
    id: 'spec-005',
    query: 'технические характеристики ESP32',
    intentType: 'specification',
    targetUrl: '/component/ESP32-WROOM-32',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['ESP32', 'характеристики', 'WiFi', 'Bluetooth'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // IMPORT SUBSTITUTION INTENTS (12)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'imp-001',
    query: 'импортозамещение STM32',
    intentType: 'import-substitution',
    targetUrl: '/analog/STM32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32', 'GD32', 'импортозамещение', 'аналоги'],
  },
  {
    id: 'imp-002',
    query: 'аналоги санкционных компонентов',
    intentType: 'import-substitution',
    targetUrl: '/analogs',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['санкции', 'аналоги', 'замена', 'Россия'],
  },
  {
    id: 'imp-003',
    query: 'замена Xilinx на Gowin',
    intentType: 'import-substitution',
    targetUrl: '/analog/Xilinx',
    priority: 1,
    covered: false,
    searchVolume: 'high',
    relatedEntities: ['Xilinx', 'Gowin', 'FPGA', 'импортозамещение'],
  },
  {
    id: 'imp-004',
    query: 'аналоги TI для РФ',
    intentType: 'import-substitution',
    targetUrl: '/analog/Texas-Instruments',
    priority: 1,
    covered: false,
    searchVolume: 'high',
    relatedEntities: ['Texas Instruments', 'аналоги', 'РФ', 'импортозамещение'],
  },
  {
    id: 'imp-005',
    query: 'российские аналоги микросхем',
    intentType: 'import-substitution',
    targetUrl: '/analogs',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['российские аналоги', 'Миландр', 'НИИЭТ', 'ВЗПП'],
  },
  {
    id: 'imp-006',
    query: 'китайские аналоги западных микросхем',
    intentType: 'import-substitution',
    targetUrl: '/analogs',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['китайские аналоги', 'GD32', 'CH32', 'Gowin'],
  },
  {
    id: 'imp-007',
    query: 'замена Altera FPGA на российские ПЛИС',
    intentType: 'import-substitution',
    targetUrl: '/analog/Altera',
    priority: 1,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['Altera', 'ПЛИС', 'импортозамещение', 'российские FPGA'],
  },
  {
    id: 'imp-008',
    query: 'аналоги NXP микроконтроллеров',
    intentType: 'import-substitution',
    targetUrl: '/analog/NXP',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['NXP', 'LPC', 'Kinetis', 'аналоги'],
  },
  {
    id: 'imp-009',
    query: 'реестр отечественных электронных компонентов',
    intentType: 'import-substitution',
    targetUrl: '/knowledge-base/reestr-otechestvennykh-komponentov',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['реестр', 'отечественные', 'Минпромторг', 'Россия'],
  },
  {
    id: 'imp-010',
    query: 'замена Analog Devices на доступные аналоги',
    intentType: 'import-substitution',
    targetUrl: '/analog/Analog-Devices',
    priority: 2,
    covered: false,
    searchVolume: 'medium',
    relatedEntities: ['Analog Devices', 'замена', 'аналоги', 'санкции'],
  },
  {
    id: 'imp-011',
    query: 'микросхемы Миландр аналоги STM32',
    intentType: 'import-substitution',
    targetUrl: '/brand/miland',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Миландр', '1886ВЕ', 'STM32', 'российские MCU'],
  },
  {
    id: 'imp-012',
    query: 'поставка компонентов в условиях санкций',
    intentType: 'import-substitution',
    targetUrl: '/import-komponentov',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['санкции', 'поставка', 'параллельный импорт', 'РФ'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // AVAILABILITY INTENTS — дополнение (8 новых)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'avail-006',
    query: 'STM32F103 в наличии',
    intentType: 'availability',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103', 'наличие', 'склад'],
  },
  {
    id: 'avail-007',
    query: 'купить FPGA в наличии',
    intentType: 'availability',
    targetUrl: '/fpga-hub',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['FPGA', 'наличие', 'ПЛИС'],
  },
  {
    id: 'avail-008',
    query: 'электронные компоненты Европа поставка',
    intentType: 'availability',
    targetUrl: '/import-komponentov',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Европа', 'поставка', 'импорт', 'компоненты'],
  },
  {
    id: 'avail-009',
    query: 'компоненты из Китая доставка',
    intentType: 'availability',
    targetUrl: '/import-komponentov',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Китай', 'доставка', 'компоненты', 'импорт'],
  },
  {
    id: 'avail-010',
    query: 'STM32 в наличии Россия',
    intentType: 'availability',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32', 'наличие', 'Россия', 'склад'],
  },
  {
    id: 'avail-011',
    query: 'GD32 купить в наличии',
    intentType: 'availability',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['GD32', 'наличие', 'купить', 'склад'],
  },
  {
    id: 'avail-012',
    query: 'Xilinx FPGA в наличии',
    intentType: 'availability',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Xilinx', 'FPGA', 'наличие', 'ПЛИС'],
  },
  {
    id: 'avail-013',
    query: 'TI компоненты склад Москва',
    intentType: 'availability',
    targetUrl: '/ti',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['TI', 'компоненты', 'склад', 'Москва'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // PRICING INTENTS — дополнение (6 новых)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'price-001',
    query: 'цена STM32F103',
    intentType: 'pricing',
    targetUrl: '/component/STM32F103C8T6',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103', 'цена', 'стоимость'],
  },
  {
    id: 'price-002',
    query: 'цена GD32F103',
    intentType: 'pricing',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['GD32F103', 'цена', 'стоимость'],
  },
  {
    id: 'price-003',
    query: 'стоимость ПЛИС Xilinx',
    intentType: 'pricing',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Xilinx', 'ПЛИС', 'стоимость', 'цена'],
  },
  {
    id: 'price-004',
    query: 'оптовая цена микроконтроллеров',
    intentType: 'pricing',
    targetUrl: '/arm-kontrollery',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['оптовая цена', 'микроконтроллеры', 'MCU', 'ARM'],
  },
  {
    id: 'price-005',
    query: 'цена LM2596 опт',
    intentType: 'pricing',
    targetUrl: '/component/LM2596',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['LM2596', 'цена', 'опт', 'DC-DC'],
  },
  {
    id: 'price-006',
    query: 'прайс электронные компоненты',
    intentType: 'pricing',
    targetUrl: '/catalog',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['прайс', 'электронные компоненты', 'цена', 'каталог'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // REPLACEMENT / MIGRATION INTENTS (8 новых)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'repl-001',
    query: 'замена Xilinx на Gowin',
    intentType: 'replacement',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Xilinx', 'Gowin', 'замена', 'миграция'],
  },
  {
    id: 'repl-002',
    query: 'миграция с Artix-7 на ECP5',
    intentType: 'replacement',
    targetUrl: '/fpga-hub',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Artix-7', 'ECP5', 'миграция', 'FPGA'],
  },
  {
    id: 'repl-003',
    query: 'аналог Cyclone V замена',
    intentType: 'replacement',
    targetUrl: '/fpga-hub',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Cyclone V', 'замена', 'FPGA', 'аналог'],
  },
  {
    id: 'repl-004',
    query: 'замена Spartan-7 на iCE40',
    intentType: 'replacement',
    targetUrl: '/xilinx',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Spartan-7', 'iCE40', 'замена', 'Lattice'],
  },
  {
    id: 'repl-005',
    query: 'миграция STM32 на GD32 руководство',
    intentType: 'replacement',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32', 'GD32', 'миграция', 'руководство'],
  },
  {
    id: 'repl-006',
    query: 'заменить TPS5430 на MP1584',
    intentType: 'replacement',
    targetUrl: '/ti',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['TPS5430', 'MP1584', 'замена', 'DC-DC'],
  },
  {
    id: 'repl-007',
    query: 'импортозамещение ПЛИС Xilinx',
    intentType: 'import-substitution',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Xilinx', 'ПЛИС', 'импортозамещение', 'Gowin'],
  },
  {
    id: 'repl-008',
    query: 'замена санкционных микросхем',
    intentType: 'import-substitution',
    targetUrl: '/analogs',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['санкции', 'замена', 'микросхемы', 'аналоги'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // PROCUREMENT / URGENT INTENTS (8 новых)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'proc-001',
    query: 'срочная закупка компонентов',
    intentType: 'bom',
    targetUrl: '/rfq',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['срочная закупка', 'компоненты', 'urgent', 'RFQ'],
  },
  {
    id: 'proc-002',
    query: 'BOM комплектация срочно',
    intentType: 'bom',
    targetUrl: '/bom',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['BOM', 'комплектация', 'срочно', 'urgent'],
  },
  {
    id: 'proc-003',
    query: 'поставщик микросхем для производства',
    intentType: 'bom',
    targetUrl: '/sourcing-expertise',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['поставщик', 'микросхемы', 'производство', 'B2B'],
  },
  {
    id: 'proc-004',
    query: 'заказать электронные компоненты для завода',
    intentType: 'bom',
    targetUrl: '/rfq',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['заказать', 'электронные компоненты', 'завод', 'RFQ'],
  },
  {
    id: 'proc-005',
    query: 'комплектация печатных плат компонентами',
    intentType: 'bom',
    targetUrl: '/bom',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['комплектация', 'печатные платы', 'компоненты', 'PCBA'],
  },
  {
    id: 'proc-006',
    query: 'поставка дефицитных микросхем',
    intentType: 'bom',
    targetUrl: '/urgent-sourcing',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['дефицитные', 'микросхемы', 'поставка', 'urgent'],
  },
  {
    id: 'proc-007',
    query: 'где купить микросхемы оптом',
    intentType: 'purchase',
    targetUrl: '/catalog',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['купить', 'микросхемы', 'оптом', 'каталог'],
  },
  {
    id: 'proc-008',
    query: 'закупка электронных компонентов предприятием',
    intentType: 'bom',
    targetUrl: '/bom',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['закупка', 'электронные компоненты', 'предприятие', 'B2B'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // PRICING INTENTS (6) — Close 24% intent gap
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'price-001',
    query: 'цена STM32F103 оптом',
    intentType: 'pricing',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103', 'цена', 'оптом', 'стоимость'],
  },
  {
    id: 'price-002',
    query: 'стоимость FPGA Artix-7',
    intentType: 'pricing',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Artix-7', 'цена', 'FPGA', 'стоимость'],
  },
  {
    id: 'price-003',
    query: 'цена LM2596 купить',
    intentType: 'pricing',
    targetUrl: '/ti',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['LM2596', 'цена', 'стабилизатор'],
  },
  {
    id: 'price-004',
    query: 'сколько стоит GD32F103',
    intentType: 'pricing',
    targetUrl: '/stm32',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['GD32F103', 'цена', 'аналог STM32'],
  },
  {
    id: 'price-005',
    query: 'цена Gowin FPGA',
    intentType: 'pricing',
    targetUrl: '/fpga-hub',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Gowin', 'FPGA', 'цена', 'ПЛИС'],
  },
  {
    id: 'price-006',
    query: 'стоимость поставки микросхем',
    intentType: 'pricing',
    targetUrl: '/rfq',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['поставка', 'стоимость', 'КП', 'коммерческое предложение'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // AVAILABILITY INTENTS (6)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'avail-001',
    query: 'STM32F103 в наличии',
    intentType: 'availability',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32F103', 'наличие', 'склад', 'доступность'],
  },
  {
    id: 'avail-002',
    query: 'FPGA Xilinx в наличии купить',
    intentType: 'availability',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Xilinx', 'FPGA', 'наличие', 'купить'],
  },
  {
    id: 'avail-003',
    query: 'GD32F103 наличие на складе',
    intentType: 'availability',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['GD32F103', 'склад', 'наличие'],
  },
  {
    id: 'avail-004',
    query: 'Gowin FPGA доступность поставка',
    intentType: 'availability',
    targetUrl: '/fpga-hub',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['Gowin', 'FPGA', 'поставка', 'доступность'],
  },
  {
    id: 'avail-005',
    query: 'LM358 в наличии Москва',
    intentType: 'availability',
    targetUrl: '/ti',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['LM358', 'наличие', 'Москва'],
  },
  {
    id: 'avail-006',
    query: 'TPS5430 доступность сроки поставки',
    intentType: 'availability',
    targetUrl: '/ti',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['TPS5430', 'сроки', 'поставка', 'TI'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // URGENCY / PROCUREMENT INTENTS (6)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'urgnt-001',
    query: 'срочная поставка STM32',
    intentType: 'purchase',
    targetUrl: '/urgent-sourcing',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['STM32', 'срочно', 'поставка', 'авиадоставка'],
  },
  {
    id: 'urgnt-002',
    query: 'экстренная замена Xilinx FPGA',
    intentType: 'replacement',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Xilinx', 'FPGA', 'замена', 'срочно'],
  },
  {
    id: 'urgnt-003',
    query: 'срочно купить микросхемы для производства',
    intentType: 'purchase',
    targetUrl: '/rfq',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['срочно', 'микросхемы', 'производство', 'КП'],
  },
  {
    id: 'urgnt-004',
    query: 'остановка производства нет компонентов',
    intentType: 'purchase',
    targetUrl: '/urgent-sourcing',
    priority: 1,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['производство', 'остановка', 'срочно', 'компоненты'],
  },
  {
    id: 'urgnt-005',
    query: 'срочная поставка FPGA для ВПК',
    intentType: 'purchase',
    targetUrl: '/fpga-hub',
    priority: 1,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['FPGA', 'ВПК', 'срочно', 'поставка'],
  },
  {
    id: 'urgnt-006',
    query: 'замена TI компонентов срочно',
    intentType: 'replacement',
    targetUrl: '/ti',
    priority: 1,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['TI', 'замена', 'срочно', 'аналог'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // CROSS-BRAND EQUIVALENCE INTENTS (6)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'xbrnd-001',
    query: 'GD32 эквивалент STM32',
    intentType: 'analog',
    targetUrl: '/stm32',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['GD32', 'STM32', 'эквивалент', 'Gigadevice'],
  },
  {
    id: 'xbrnd-002',
    query: 'Gowin альтернатива Xilinx',
    intentType: 'analog',
    targetUrl: '/xilinx',
    priority: 1,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['Gowin', 'Xilinx', 'альтернатива', 'FPGA'],
  },
  {
    id: 'xbrnd-003',
    query: 'MP1584 замена TPS5430',
    intentType: 'replacement',
    targetUrl: '/ti',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['MP1584', 'TPS5430', 'замена', 'DC-DC'],
  },
  {
    id: 'xbrnd-004',
    query: 'ECP5 аналог Artix-7',
    intentType: 'analog',
    targetUrl: '/fpga-hub',
    priority: 1,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['ECP5', 'Artix-7', 'Lattice', 'аналог'],
  },
  {
    id: 'xbrnd-005',
    query: 'XL2596 эквивалент LM2596',
    intentType: 'analog',
    targetUrl: '/ti',
    priority: 2,
    covered: true,
    searchVolume: 'high',
    relatedEntities: ['XL2596', 'LM2596', 'XLSEMI', 'эквивалент'],
  },
  {
    id: 'xbrnd-006',
    query: 'Lattice iCE40 замена Spartan',
    intentType: 'replacement',
    targetUrl: '/fpga-hub',
    priority: 2,
    covered: true,
    searchVolume: 'medium',
    relatedEntities: ['iCE40', 'Spartan', 'Lattice', 'замена'],
  },
];

// ─── Вычисляемые массивы и группы ──────────────────────────────────────────────

/** Все непокрытые интенты, отсортированные по приоритету (1 = высший) */
export const intentCoverageGaps: SearchIntent[] = [...searchIntents]
  .filter((intent) => !intent.covered)
  .sort((a, b) => a.priority - b.priority);

/** Группировка интентов по типу */
export const intentGroupsByType: Record<string, SearchIntent[]> = searchIntents.reduce<
  Record<string, SearchIntent[]>
>((acc, intent) => {
  const type = intent.intentType;
  if (!acc[type]) {
    acc[type] = [];
  }
  acc[type].push(intent);
  return acc;
}, {});

// ─── Вспомогательные функции ───────────────────────────────────────────────────

/**
 * Найти интенты, соответствующие поисковому запросу.
 * Поиск ведётся по вхождению подстроки в поле query (без учёта регистра).
 */
export function getIntentForQuery(query: string): SearchIntent[] {
  const normalizedQuery = query.toLowerCase().trim();
  return searchIntents.filter((intent) => intent.query.toLowerCase().includes(normalizedQuery));
}

/**
 * Получить все непокрытые интенты, отсортированные по приоритету.
 */
export function getUncoveredIntents(): SearchIntent[] {
  return intentCoverageGaps;
}

/**
 * Рассчитать процент покрытия интентов существующими страницами.
 */
export function getCoveragePercentage(): number {
  if (searchIntents.length === 0) return 0;
  const coveredCount = searchIntents.filter((i) => i.covered).length;
  return Math.round((coveredCount / searchIntents.length) * 100);
}

/**
 * Найти все интенты, связанные с определённой сущностью.
 * Поиск по массиву relatedEntities (без учёта регистра).
 */
export function getIntentsByEntity(entityId: string): SearchIntent[] {
  const normalizedEntity = entityId.toLowerCase().trim();
  return searchIntents.filter((intent) =>
    intent.relatedEntities.some((entity) => entity.toLowerCase().includes(normalizedEntity))
  );
}

/**
 * Получить все интенты заданного типа.
 */
export function getIntentsByType(type: string): SearchIntent[] {
  return intentGroupsByType[type] ?? [];
}

/**
 * Получить высокоприоритетные непокрытые интенты (приоритет 1–3).
 * Используется для приоритизации создания новых посадочных страниц.
 */
export function getHighPriorityUncovered(): SearchIntent[] {
  return intentCoverageGaps.filter((intent) => intent.priority <= 3);
}
